/** Export the highest layer as Component itself (with Props). Renaming is mandatory. */
export { DevelopmentPageConnect as DevelopmentPage, Props as DevelopmentPageProps } from './DevelopmentPageConnect';

/** In case of theme, export ThemeName. Renaming is mandatory. */
export { ThemeName as DevelopmentPageThemeName } from './DevelopmentPageTemplate';

/** Re-export autogenerated apollo types to use them outside of origin component */
export { License } from './ApolloTypes/License';
