/** Export the highest layer as Component itself (with Props). Renaming is mandatory. */
export { DevelopmentPageConnect as DevelopmentPage, Props as DevelopmentPageProps } from './DevelopmentPageConnect';

/** Re-export autogenerated apollo types to use them outside of origin component */
export { BookFull } from './ApolloTypes/BookFull';
