/** Export the highest layer as Component itself (with Props). Renaming is mandatory. */
export { DevelopmentPage, Props as DevelopmentPageProps } from './DevelopmentPage';

/** Re-export autogenerated apollo types to use them outside of origin component */
export { BookFull } from './ApolloTypes/BookFull';
